package com.whw.study.entity;

import io.swagger.annotations.ApiModelProperty;

public class Dict {
    /**
     *
     * This field was generated by New MyBatis Generator.
     * This field corresponds to the database column dicts.dict_code
     *
     * @mbg.generated
     */
    @ApiModelProperty("字典代号")
    private String dictCode;

    /**
     *
     * This field was generated by New MyBatis Generator.
     * This field corresponds to the database column dicts.dict_name
     *
     * @mbg.generated
     */
    @ApiModelProperty("字典名称,国际化处理")
    private String dictName;

    /**
     *
     * This field was generated by New MyBatis Generator.
     * This field corresponds to the database column dicts.dict_remark
     *
     * @mbg.generated
     */
    @ApiModelProperty("备注")
    private String dictRemark;

    /**
     *
     * This field was generated by New MyBatis Generator.
     * This field corresponds to the database column dicts.support_i18n
     *
     * @mbg.generated
     */
    @ApiModelProperty("是否支持国际化")
    private Boolean supportI18n;

    /**
     * This method was generated by New MyBatis Generator.
     * This method returns the value of the database column dicts.dict_code
     *
     * @return the value of dicts.dict_code
     *
     * @mbg.generated
     */
    public String getDictCode() {
        return dictCode;
    }

    /**
     * This method was generated by New MyBatis Generator.
     * This method sets the value of the database column dicts.dict_code
     *
     * @param dictCode the value for dicts.dict_code
     *
     * @mbg.generated
     */
    public void setDictCode(String dictCode) {
        this.dictCode = dictCode == null ? null : dictCode.trim();
    }

    /**
     * This method was generated by New MyBatis Generator.
     * This method returns the value of the database column dicts.dict_name
     *
     * @return the value of dicts.dict_name
     *
     * @mbg.generated
     */
    public String getDictName() {
        return dictName;
    }

    /**
     * This method was generated by New MyBatis Generator.
     * This method sets the value of the database column dicts.dict_name
     *
     * @param dictName the value for dicts.dict_name
     *
     * @mbg.generated
     */
    public void setDictName(String dictName) {
        this.dictName = dictName == null ? null : dictName.trim();
    }

    /**
     * This method was generated by New MyBatis Generator.
     * This method returns the value of the database column dicts.dict_remark
     *
     * @return the value of dicts.dict_remark
     *
     * @mbg.generated
     */
    public String getDictRemark() {
        return dictRemark;
    }

    /**
     * This method was generated by New MyBatis Generator.
     * This method sets the value of the database column dicts.dict_remark
     *
     * @param dictRemark the value for dicts.dict_remark
     *
     * @mbg.generated
     */
    public void setDictRemark(String dictRemark) {
        this.dictRemark = dictRemark == null ? null : dictRemark.trim();
    }

    /**
     * This method was generated by New MyBatis Generator.
     * This method returns the value of the database column dicts.support_i18n
     *
     * @return the value of dicts.support_i18n
     *
     * @mbg.generated
     */
    public Boolean getSupportI18n() {
        return supportI18n;
    }

    /**
     * This method was generated by New MyBatis Generator.
     * This method sets the value of the database column dicts.support_i18n
     *
     * @param supportI18n the value for dicts.support_i18n
     *
     * @mbg.generated
     */
    public void setSupportI18n(Boolean supportI18n) {
        this.supportI18n = supportI18n;
    }

    /**
     * This method was generated by New MyBatis Generator.
     * This method corresponds to the database table dicts
     *
     * @mbg.generated
     */
    public String test() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", dictCode=").append(dictCode);
        sb.append(", dictName=").append(dictName);
        sb.append(", dictRemark=").append(dictRemark);
        sb.append(", supportI18n=").append(supportI18n);
        sb.append("]");
        return sb.toString();
    }
}