package com.whw.study.mapper;

import com.whw.study.entity.Dict;
import com.whw.study.entity.example.DictExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DictMapper {
    /**
     * This method was generated by New MyBatis Generator.
     * This method corresponds to the database table dicts
     *
     * @mbg.generated
     */
    long countByExample(DictExample example);

    /**
     * This method was generated by New MyBatis Generator.
     * This method corresponds to the database table dicts
     *
     * @mbg.generated
     */
    int deleteByExample(DictExample example);

    /**
     * This method was generated by New MyBatis Generator.
     * This method corresponds to the database table dicts
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String dictCode);

    /**
     * This method was generated by New MyBatis Generator.
     * This method corresponds to the database table dicts
     *
     * @mbg.generated
     */
    int insert(Dict record);

    /**
     * This method was generated by New MyBatis Generator.
     * This method corresponds to the database table dicts
     *
     * @mbg.generated
     */
    int insertSelective(Dict record);

    /**
     * This method was generated by New MyBatis Generator.
     * This method corresponds to the database table dicts
     *
     * @mbg.generated
     */
    List<Dict> selectByExample(DictExample example);

    /**
     * This method was generated by New MyBatis Generator.
     * This method corresponds to the database table dicts
     *
     * @mbg.generated
     */
    Dict selectByPrimaryKey(String dictCode);

    /**
     * This method was generated by New MyBatis Generator.
     * This method corresponds to the database table dicts
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Dict record, @Param("example") DictExample example);

    /**
     * This method was generated by New MyBatis Generator.
     * This method corresponds to the database table dicts
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Dict record, @Param("example") DictExample example);

    /**
     * This method was generated by New MyBatis Generator.
     * This method corresponds to the database table dicts
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Dict record);

    /**
     * This method was generated by New MyBatis Generator.
     * This method corresponds to the database table dicts
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Dict record);
}