package com.whw.study.entity.example;

import java.util.ArrayList;
import java.util.List;

public class DictExample {
    /**
     * This field was generated by New MyBatis Generator.
     * This field corresponds to the database table dicts
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by New MyBatis Generator.
     * This field corresponds to the database table dicts
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by New MyBatis Generator.
     * This field corresponds to the database table dicts
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by New MyBatis Generator.
     * This method corresponds to the database table dicts
     *
     * @mbg.generated
     */
    public DictExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by New MyBatis Generator.
     * This method corresponds to the database table dicts
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by New MyBatis Generator.
     * This method corresponds to the database table dicts
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by New MyBatis Generator.
     * This method corresponds to the database table dicts
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by New MyBatis Generator.
     * This method corresponds to the database table dicts
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by New MyBatis Generator.
     * This method corresponds to the database table dicts
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by New MyBatis Generator.
     * This method corresponds to the database table dicts
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by New MyBatis Generator.
     * This method corresponds to the database table dicts
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by New MyBatis Generator.
     * This method corresponds to the database table dicts
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by New MyBatis Generator.
     * This method corresponds to the database table dicts
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by New MyBatis Generator.
     * This method corresponds to the database table dicts
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by New MyBatis Generator.
     * This class corresponds to the database table dicts
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDictCodeIsNull() {
            addCriterion("dict_code is null");
            return (Criteria) this;
        }

        public Criteria andDictCodeIsNotNull() {
            addCriterion("dict_code is not null");
            return (Criteria) this;
        }

        public Criteria andDictCodeEqualTo(String value) {
            addCriterion("dict_code =", value, "dictCode");
            return (Criteria) this;
        }

        public Criteria andDictCodeNotEqualTo(String value) {
            addCriterion("dict_code <>", value, "dictCode");
            return (Criteria) this;
        }

        public Criteria andDictCodeGreaterThan(String value) {
            addCriterion("dict_code >", value, "dictCode");
            return (Criteria) this;
        }

        public Criteria andDictCodeGreaterThanOrEqualTo(String value) {
            addCriterion("dict_code >=", value, "dictCode");
            return (Criteria) this;
        }

        public Criteria andDictCodeLessThan(String value) {
            addCriterion("dict_code <", value, "dictCode");
            return (Criteria) this;
        }

        public Criteria andDictCodeLessThanOrEqualTo(String value) {
            addCriterion("dict_code <=", value, "dictCode");
            return (Criteria) this;
        }

        public Criteria andDictCodeLike(String value) {
            addCriterion("dict_code like", value, "dictCode");
            return (Criteria) this;
        }

        public Criteria andDictCodeNotLike(String value) {
            addCriterion("dict_code not like", value, "dictCode");
            return (Criteria) this;
        }

        public Criteria andDictCodeIn(List<String> values) {
            addCriterion("dict_code in", values, "dictCode");
            return (Criteria) this;
        }

        public Criteria andDictCodeNotIn(List<String> values) {
            addCriterion("dict_code not in", values, "dictCode");
            return (Criteria) this;
        }

        public Criteria andDictCodeBetween(String value1, String value2) {
            addCriterion("dict_code between", value1, value2, "dictCode");
            return (Criteria) this;
        }

        public Criteria andDictCodeNotBetween(String value1, String value2) {
            addCriterion("dict_code not between", value1, value2, "dictCode");
            return (Criteria) this;
        }

        public Criteria andDictNameIsNull() {
            addCriterion("dict_name is null");
            return (Criteria) this;
        }

        public Criteria andDictNameIsNotNull() {
            addCriterion("dict_name is not null");
            return (Criteria) this;
        }

        public Criteria andDictNameEqualTo(String value) {
            addCriterion("dict_name =", value, "dictName");
            return (Criteria) this;
        }

        public Criteria andDictNameNotEqualTo(String value) {
            addCriterion("dict_name <>", value, "dictName");
            return (Criteria) this;
        }

        public Criteria andDictNameGreaterThan(String value) {
            addCriterion("dict_name >", value, "dictName");
            return (Criteria) this;
        }

        public Criteria andDictNameGreaterThanOrEqualTo(String value) {
            addCriterion("dict_name >=", value, "dictName");
            return (Criteria) this;
        }

        public Criteria andDictNameLessThan(String value) {
            addCriterion("dict_name <", value, "dictName");
            return (Criteria) this;
        }

        public Criteria andDictNameLessThanOrEqualTo(String value) {
            addCriterion("dict_name <=", value, "dictName");
            return (Criteria) this;
        }

        public Criteria andDictNameLike(String value) {
            addCriterion("dict_name like", value, "dictName");
            return (Criteria) this;
        }

        public Criteria andDictNameNotLike(String value) {
            addCriterion("dict_name not like", value, "dictName");
            return (Criteria) this;
        }

        public Criteria andDictNameIn(List<String> values) {
            addCriterion("dict_name in", values, "dictName");
            return (Criteria) this;
        }

        public Criteria andDictNameNotIn(List<String> values) {
            addCriterion("dict_name not in", values, "dictName");
            return (Criteria) this;
        }

        public Criteria andDictNameBetween(String value1, String value2) {
            addCriterion("dict_name between", value1, value2, "dictName");
            return (Criteria) this;
        }

        public Criteria andDictNameNotBetween(String value1, String value2) {
            addCriterion("dict_name not between", value1, value2, "dictName");
            return (Criteria) this;
        }

        public Criteria andDictRemarkIsNull() {
            addCriterion("dict_remark is null");
            return (Criteria) this;
        }

        public Criteria andDictRemarkIsNotNull() {
            addCriterion("dict_remark is not null");
            return (Criteria) this;
        }

        public Criteria andDictRemarkEqualTo(String value) {
            addCriterion("dict_remark =", value, "dictRemark");
            return (Criteria) this;
        }

        public Criteria andDictRemarkNotEqualTo(String value) {
            addCriterion("dict_remark <>", value, "dictRemark");
            return (Criteria) this;
        }

        public Criteria andDictRemarkGreaterThan(String value) {
            addCriterion("dict_remark >", value, "dictRemark");
            return (Criteria) this;
        }

        public Criteria andDictRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("dict_remark >=", value, "dictRemark");
            return (Criteria) this;
        }

        public Criteria andDictRemarkLessThan(String value) {
            addCriterion("dict_remark <", value, "dictRemark");
            return (Criteria) this;
        }

        public Criteria andDictRemarkLessThanOrEqualTo(String value) {
            addCriterion("dict_remark <=", value, "dictRemark");
            return (Criteria) this;
        }

        public Criteria andDictRemarkLike(String value) {
            addCriterion("dict_remark like", value, "dictRemark");
            return (Criteria) this;
        }

        public Criteria andDictRemarkNotLike(String value) {
            addCriterion("dict_remark not like", value, "dictRemark");
            return (Criteria) this;
        }

        public Criteria andDictRemarkIn(List<String> values) {
            addCriterion("dict_remark in", values, "dictRemark");
            return (Criteria) this;
        }

        public Criteria andDictRemarkNotIn(List<String> values) {
            addCriterion("dict_remark not in", values, "dictRemark");
            return (Criteria) this;
        }

        public Criteria andDictRemarkBetween(String value1, String value2) {
            addCriterion("dict_remark between", value1, value2, "dictRemark");
            return (Criteria) this;
        }

        public Criteria andDictRemarkNotBetween(String value1, String value2) {
            addCriterion("dict_remark not between", value1, value2, "dictRemark");
            return (Criteria) this;
        }

        public Criteria andSupportI18nIsNull() {
            addCriterion("support_i18n is null");
            return (Criteria) this;
        }

        public Criteria andSupportI18nIsNotNull() {
            addCriterion("support_i18n is not null");
            return (Criteria) this;
        }

        public Criteria andSupportI18nEqualTo(Boolean value) {
            addCriterion("support_i18n =", value, "supportI18n");
            return (Criteria) this;
        }

        public Criteria andSupportI18nNotEqualTo(Boolean value) {
            addCriterion("support_i18n <>", value, "supportI18n");
            return (Criteria) this;
        }

        public Criteria andSupportI18nGreaterThan(Boolean value) {
            addCriterion("support_i18n >", value, "supportI18n");
            return (Criteria) this;
        }

        public Criteria andSupportI18nGreaterThanOrEqualTo(Boolean value) {
            addCriterion("support_i18n >=", value, "supportI18n");
            return (Criteria) this;
        }

        public Criteria andSupportI18nLessThan(Boolean value) {
            addCriterion("support_i18n <", value, "supportI18n");
            return (Criteria) this;
        }

        public Criteria andSupportI18nLessThanOrEqualTo(Boolean value) {
            addCriterion("support_i18n <=", value, "supportI18n");
            return (Criteria) this;
        }

        public Criteria andSupportI18nIn(List<Boolean> values) {
            addCriterion("support_i18n in", values, "supportI18n");
            return (Criteria) this;
        }

        public Criteria andSupportI18nNotIn(List<Boolean> values) {
            addCriterion("support_i18n not in", values, "supportI18n");
            return (Criteria) this;
        }

        public Criteria andSupportI18nBetween(Boolean value1, Boolean value2) {
            addCriterion("support_i18n between", value1, value2, "supportI18n");
            return (Criteria) this;
        }

        public Criteria andSupportI18nNotBetween(Boolean value1, Boolean value2) {
            addCriterion("support_i18n not between", value1, value2, "supportI18n");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by New MyBatis Generator.
     * This class corresponds to the database table dicts
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by New MyBatis Generator.
     * This class corresponds to the database table dicts
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}